### ISSUE TITLE
Issue loading sqlite file

### ISSUE THREAD

**Issue by sudhaharv77** [tomtom-international/openlr#30]
I have used openlr to load sqlite file to generate openlr.map.MapDatabase using Spring boot application, I can able to convert if i used normal java project. But if i use with spring boot i am facing the below issue,

Can pleas help, below is the stack trace.

openlr.map.loader.OpenLRMapLoaderException: Cannot load SQLite database
	at openlr.map.sqlite.loader.SQLiteMapLoader.load(SQLiteMapLoader.java:73)
	at com.stee.trafficdata.service.impl.TrafficDataServiceImpl.loadSqLiteData(TrafficDataServiceImpl.java:72)
	at com.stee.trafficdata.starter.TrafficDataStarter.run(TrafficDataStarter.java:20)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.stee.trafficdata.TrafficdataApplication.main(TrafficdataApplication.java:12)
Caused by: java.lang.IllegalStateException: Unable to open database connection.
	at openlr.map.sqlite.impl.MapDatabaseImpl.<init>(MapDatabaseImpl.java:179)
	at openlr.map.sqlite.loader.SQLiteMapLoader.load(SQLiteMapLoader.java:71)
	... 8 more
Caused by: java.sql.SQLException: Cannot change read-only flag after establishing a connection. Use SQLiteConfig#setReadOnly and SQLiteConfig.createConnection().
	at org.sqlite.jdbc3.JDBC3Connection.setReadOnly(JDBC3Connection.java:112)
	at openlr.map.sqlite.impl.MapDatabaseImpl.getDatabaseConnection(MapDatabaseImpl.java:343)
	at openlr.map.sqlite.impl.MapDatabaseImpl.<init>(MapDatabaseImpl.java:175)
	... 9 more

**Comment by stephencurran** [comment]
Thanks for the report.  Could you help us by posting the code snippet that is causing this exception?

**Comment by sudhaharv77** [comment]
Hi Stephencurran,

Please find the git repo for the code and image as attached, looking for your suggestions

Thanks

https://github.com/sudhaharv77/tomtomOpenlr

![Issue](https://user-images.githubusercontent.com/32642452/70293552-9454f200-181b-11ea-9828-fd74f946ce91.PNG)

**Comment by stephencurran** [comment]
Thanks for providing more information and the screenshot. The stack-trace suggests that the map loader is not able to establish a connection to the database.

It would be great if you could check that the file `tomtom_dubai.db3`
-  exists in the location specified
-  is an sqlite file and has the schema described here: https://github.com/tomtom-international/openlr/blob/master/maploader-tt-sqlite/src/main/resources/schema.sql

You can find out the schema of the database by opening a shell, changing into the directory containing the database file and executing
```
sqlite3 tomtom_dubai.db3 .schema
```

**Comment by sudhaharv77** [comment]
Hi, Thanks for your kind response.

Please find the attached screen shot(file not able to attached, because of size).

Here i have 2 things to tell.

 same file i can able to do with normal java project. I just want try to implement spring boot,
that time i face the issue.
i think the db3 file ok. please find attched screen shot
![Capture](https://user-images.githubusercontent.com/32642452/70368363-a3ec3d80-18e4-11ea-93a4-b56de1772763.PNG)

And also i have serious issue with Decode Method, return response is very slow. Please look my
project in https://github.com/sudhaharv77/trafficdata_JavaOnly
When try to do openlr decoding, its taking more time to return response.
I have 43k records to decode, its take almost 40 mins.
could you please help to sort out the issue.






Thanks
